# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
AWSTemplateFormatVersion: 2010-09-09
Description: Our first template in CloudFormation course.
Resources:
  # Demo-1 creates an EC2 instance
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ee679ef733e3b8e7
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: Demo-1 server
