# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
AWSTemplateFormatVersion: 2010-09-09
Description: Our first template in CloudFormation course.
Resources:
  # #1 Creates instances
  WebServerInstance1:
    DependsOn: CustomVpcSubnet
    DependsOn: ALBSecurityGroup
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ca-central-1a
      ImageId: ami-0ee679ef733e3b8e7
      InstanceType: t2.micro
      SubnetId: !Ref CustomVpcSubnet1
      # # Attaches the "Web server security group" to the EC2 instance "Web server"
      SecurityGroupIds:
        - !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: Demo-1 server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Use this for your user data (script from top to bottom)
          # install httpd (Linux 2 version)
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello World from $(hostname -f)</h1>" > /var/www/html/index.html
  WebServerInstance2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ca-central-1a
      ImageId: ami-0ee679ef733e3b8e7
      InstanceType: t2.micro
      SubnetId: !Ref CustomVpcSubnet1
      # # Attaches the "Web server security group" to the EC2 instance "Web server"
      SecurityGroupIds:
        - !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: Demo-2 server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Use this for your user data (script from top to bottom)
          # install httpd (Linux 2 version)
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello World from $(hostname -f)</h1>" > /var/www/html/index.html
  WebServerInstance3:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ca-central-1b
      ImageId: ami-0ee679ef733e3b8e7
      InstanceType: t2.micro
      SubnetId: !Ref CustomVpcSubnet2
      # # Attaches the "Web server security group" to the EC2 instance "Web server"
      SecurityGroupIds:
        - !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: Demo-3 server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Use this for your user data (script from top to bottom)
          # install httpd (Linux 2 version)
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello World from $(hostname -f)</h1>" > /var/www/html/index.html
  # # 2 creates a security group for ALB and EC2 instances
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref CustomVpc
      GroupDescription: ALB Security group for web servers
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: ALB server security group
  # 3 Target group
  ALBTargetGroup:
    DependsOn: CustomVpc
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 7
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !Ref CustomVpc
      TargetType: instance
      Targets:
        - Id: !Ref WebServerInstance1
          Port: 80
        - Id: !Ref WebServerInstance2
          Port: 80
        - Id: !Ref WebServerInstance3
          Port: 80
      VpcId: !Ref CustomVpc
      Tags:
        - Key: Name
          Value: Demo-TG
  # 4 creating a VPC with subnets
  CustomVpc:
    Type: AWS::EC2::VPC
    Description: VPC FOR ALB and EC2 Instances
    Properties:
      CidrBlock: 10.16.0.0/16
      # CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: CustomVpc

  CustomVpcSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ca-central-1a
      CidrBlock: 10.16.0.0/20
      # CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref CustomVpc
  CustomVpcSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ca-central-1b
      CidrBlock: 10.16.64.0/20
      # CidrBlock: 10.0.0.0/25
      MapPublicIpOnLaunch: true
      VpcId: !Ref CustomVpc

  CustomVpcRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref CustomVpc

  CustomVpcInternetGateway:
    Type: AWS::EC2::InternetGateway

  CustomVpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref CustomVpc
      InternetGatewayId: !Ref CustomVpcInternetGateway

  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn:
      - CustomVpcGatewayAttachment
    Properties:
      RouteTableId: !Ref CustomVpcRouteTable
      GatewayId: !Ref CustomVpcInternetGateway
      DestinationCidrBlock: 0.0.0.0/0

  CustomVpcSubnetRouteTableAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref CustomVpcRouteTable
      SubnetId: !Ref CustomVpcSubnet1

  CustomVpcSubnetRouteTableAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref CustomVpcRouteTable
      SubnetId: !Ref CustomVpcSubnet2

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: My-ALB
      Subnets:
        - !Ref CustomVpcSubnet1
        - !Ref CustomVpcSubnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
